import localFont from "next/font/local";
import "./globals.css";
import { GlobalStateProvider } from "./GlobalStateProvider";
import ClientLayout from "./ClientLayout";
import ThemeProvider from "./ThemeProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "iSANS Products",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <GlobalStateProvider>
          <ClientLayout>
            <ThemeProvider>
        {children}
            </ThemeProvider>
          </ClientLayout>
        </GlobalStateProvider>
      </body>
    </html>
  );
}
