import React from "react";
import Sidebar from "./sidebar/Sidebar";

export const metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};

const Layout = ({ children }) => {
  return (
    <div className="min-h-screen bg-[var(--bg-primary)] overflow-auto">
      <Sidebar />
      <main className="transition-all duration-300 pt-16 md:pt-0 md:ml-[15%] px-4">
        <div className="container mx-auto py-6">{children}</div>
      </main>
    </div>
  );
};

export default Layout;
