// 'use client'; // Ensure this is a client component

import React from 'react';
import Sidebar from './sidebar/Sidebar';
export const metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};

const Layout = ({ children }) => {
 return (
    <>
      <Sidebar />
      <div className="pt-20 sm:pl-28 pl-6">
        {children}
      </div>
    </>
  );
};

export default Layout;
